# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marco Poetry Chen
email: marcopchen@gmail.com
description: Yes, that's my real middle name.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcopchen.github.io/" # the base hostname & protocol for your site
twitter_username: marcopchen
github_username:  marcopchen
paginate: 5
theme-dark: false #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
